package com.fbt.dao.entities;

// Generated Mar 31, 2015 1:18:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BetaValueMaster generated by hbm2java
 */
@Entity
@Table(name = "beta_value_master", catalog = "talentex_sme")
public class BetaValueMaster implements java.io.Serializable {

	private Integer id;
	private JobRoleTechMaster jobRoleTechMaster;
	private DegreeMaster degreeMaster;
	private double weightage;

	public BetaValueMaster() {
	}

	public BetaValueMaster(JobRoleTechMaster jobRoleTechMaster,
			DegreeMaster degreeMaster, double weightage) {
		this.jobRoleTechMaster = jobRoleTechMaster;
		this.degreeMaster = degreeMaster;
		this.weightage = weightage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_role_tech_master_id", nullable = false)
	public JobRoleTechMaster getJobRoleTechMaster() {
		return this.jobRoleTechMaster;
	}

	public void setJobRoleTechMaster(JobRoleTechMaster jobRoleTechMaster) {
		this.jobRoleTechMaster = jobRoleTechMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "degree_master_id", nullable = false)
	public DegreeMaster getDegreeMaster() {
		return this.degreeMaster;
	}

	public void setDegreeMaster(DegreeMaster degreeMaster) {
		this.degreeMaster = degreeMaster;
	}

	@Column(name = "weightage", nullable = false, precision = 22, scale = 0)
	public double getWeightage() {
		return this.weightage;
	}

	public void setWeightage(double weightage) {
		this.weightage = weightage;
	}

}
