package com.fbt.dao.entities;

// Generated Mar 31, 2015 1:18:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CourseJobtechnologyMapping generated by hbm2java
 */
@Entity
@Table(name = "course_jobtechnology_mapping", catalog = "talentex_sme")
public class CourseJobtechnologyMapping implements java.io.Serializable {

	private Integer id;
	private JobRoleTechMaster jobRoleTechMaster;
	private CourseMaster courseMaster;
	private int weightage;

	public CourseJobtechnologyMapping() {
	}

	public CourseJobtechnologyMapping(JobRoleTechMaster jobRoleTechMaster,
			CourseMaster courseMaster, int weightage) {
		this.jobRoleTechMaster = jobRoleTechMaster;
		this.courseMaster = courseMaster;
		this.weightage = weightage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_role_tech_master_id", nullable = false)
	public JobRoleTechMaster getJobRoleTechMaster() {
		return this.jobRoleTechMaster;
	}

	public void setJobRoleTechMaster(JobRoleTechMaster jobRoleTechMaster) {
		this.jobRoleTechMaster = jobRoleTechMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_master_id", nullable = false)
	public CourseMaster getCourseMaster() {
		return this.courseMaster;
	}

	public void setCourseMaster(CourseMaster courseMaster) {
		this.courseMaster = courseMaster;
	}

	@Column(name = "weightage", nullable = false)
	public int getWeightage() {
		return this.weightage;
	}

	public void setWeightage(int weightage) {
		this.weightage = weightage;
	}

}
