package com.fbt.dao.entities;
// Generated Mar 31, 2015 1:18:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseMaster generated by hbm2java
 */
@Entity
@Table(name = "course_master", catalog = "talentex_sme")
public class CourseMaster implements java.io.Serializable {

	private Integer id;
	private String courseCode;
	private String courseName;
	private String category;
	private Set<QuestionMaster> questionMasters = new HashSet<QuestionMaster>();
	private Set<CourseJobtechnologyMapping> courseJobtechnologyMappings = new HashSet<CourseJobtechnologyMapping>();

	public CourseMaster() {
	}

	public CourseMaster(String courseCode, String courseName, String category) {
		this.courseCode = courseCode;
		this.courseName = courseName;
		this.category = category;
	}

	public CourseMaster(String courseCode, String courseName, String category,
			Set<QuestionMaster> questionMasters, Set<CourseJobtechnologyMapping> courseJobtechnologyMappings) {
		this.courseCode = courseCode;
		this.courseName = courseName;
		this.category = category;
		this.questionMasters = questionMasters;
		this.courseJobtechnologyMappings = courseJobtechnologyMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "course_code", nullable = false, length = 10)
	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	@Column(name = "course_name", nullable = false, length = 150)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "category", nullable = false, length = 2)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseMaster")
	public Set<QuestionMaster> getQuestionMasters() {
		return this.questionMasters;
	}

	public void setQuestionMasters(Set<QuestionMaster> questionMasters) {
		this.questionMasters = questionMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseMaster")
	public Set<CourseJobtechnologyMapping> getCourseJobtechnologyMappings() {
		return this.courseJobtechnologyMappings;
	}

	public void setCourseJobtechnologyMappings(Set<CourseJobtechnologyMapping> courseJobtechnologyMappings) {
		this.courseJobtechnologyMappings = courseJobtechnologyMappings;
	}

}
