package com.fbt.dao.entities;

// Generated Mar 31, 2015 1:18:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndustryMaster generated by hbm2java
 */
@Entity
@Table(name = "industry_master", catalog = "talentex_sme")
public class IndustryMaster implements java.io.Serializable {

	private Integer id;
	private String industryName;
	private Set<JobRoleMaster> jobRoleMasters = new HashSet<JobRoleMaster>();

	public IndustryMaster() {
	}

	public IndustryMaster(String industryName) {
		this.industryName = industryName;
	}

	public IndustryMaster(String industryName, Set<JobRoleMaster> jobRoleMasters) {
		this.industryName = industryName;
		this.jobRoleMasters = jobRoleMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "industry_name", nullable = false)
	public String getIndustryName() {
		return this.industryName;
	}

	public void setIndustryName(String industryName) {
		this.industryName = industryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industryMaster")
	public Set<JobRoleMaster> getJobRoleMasters() {
		return this.jobRoleMasters;
	}

	public void setJobRoleMasters(Set<JobRoleMaster> jobRoleMasters) {
		this.jobRoleMasters = jobRoleMasters;
	}

}
