package com.fbt.dao.entities;

// Generated Mar 31, 2015 1:18:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobRoleTechMaster generated by hbm2java
 */
@Entity
@Table(name = "job_role_tech_master", catalog = "talentex_sme")
public class JobRoleTechMaster implements java.io.Serializable {

	private Integer id;
	private JobRoleMaster jobRoleMaster;
	private String jobTechnologyName;
	private Set<BetaValueMaster> betaValueMasters = new HashSet<BetaValueMaster>();
	private Set<CourseJobtechnologyMapping> courseJobtechnologyMappings = new HashSet<CourseJobtechnologyMapping>();

	public JobRoleTechMaster() {
	}

	public JobRoleTechMaster(JobRoleMaster jobRoleMaster,
			String jobTechnologyName) {
		this.jobRoleMaster = jobRoleMaster;
		this.jobTechnologyName = jobTechnologyName;
	}

	public JobRoleTechMaster(JobRoleMaster jobRoleMaster,
			String jobTechnologyName, Set<BetaValueMaster> betaValueMasters,
			Set<CourseJobtechnologyMapping> courseJobtechnologyMappings) {
		this.jobRoleMaster = jobRoleMaster;
		this.jobTechnologyName = jobTechnologyName;
		this.betaValueMasters = betaValueMasters;
		this.courseJobtechnologyMappings = courseJobtechnologyMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_role_master_id", nullable = false)
	public JobRoleMaster getJobRoleMaster() {
		return this.jobRoleMaster;
	}

	public void setJobRoleMaster(JobRoleMaster jobRoleMaster) {
		this.jobRoleMaster = jobRoleMaster;
	}

	@Column(name = "job_technology_name", nullable = false)
	public String getJobTechnologyName() {
		return this.jobTechnologyName;
	}

	public void setJobTechnologyName(String jobTechnologyName) {
		this.jobTechnologyName = jobTechnologyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRoleTechMaster")
	public Set<BetaValueMaster> getBetaValueMasters() {
		return this.betaValueMasters;
	}

	public void setBetaValueMasters(Set<BetaValueMaster> betaValueMasters) {
		this.betaValueMasters = betaValueMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRoleTechMaster")
	public Set<CourseJobtechnologyMapping> getCourseJobtechnologyMappings() {
		return this.courseJobtechnologyMappings;
	}

	public void setCourseJobtechnologyMappings(Set<CourseJobtechnologyMapping> courseJobtechnologyMappings) {
		this.courseJobtechnologyMappings = courseJobtechnologyMappings;
	}

}
