package com.fbt.dao.entities;

// Generated Jun 16, 2015 11:26:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Option generated by hbm2java
 */
@Entity
@Table(name = "options", catalog = "talentex_mocktest")
public class Options implements java.io.Serializable {

	private Integer id;
	private Question question;
	private String options;
	private int answer;

	public Options() {
	}

	public Options(Question question, String options, int answer) {
		this.question = question;
		this.options = options;
		this.answer = answer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "options", nullable = false, length = 100)
	public String getOption() {
		return this.options;
	}

	public void setOption(String options) {
		this.options = options;
	}

	@Column(name = "answer", nullable = false)
	public int getAnswer() {
		return this.answer;
	}

	public void setAnswer(int answer) {
		this.answer = answer;
	}

}
