package com.fbt.dao.entities;

// Generated Jun 16, 2015 11:26:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "talentex_mocktest")
public class Question implements java.io.Serializable {

	private Integer id;
	private IndustrySkill industrySkill;
	private String question;
	private int mark;
	private String level;
	private Set<Options> options = new HashSet<Options>();

	public Question() {
	}

	public Question(IndustrySkill industrySkill, String question, int mark, String level) {
		this.industrySkill = industrySkill;
		this.question = question;
		this.mark = mark;
		this.level = level;
	}

	public Question(IndustrySkill industrySkill, String question, Set<Options> options, int mark, String level) {
		this.industrySkill = industrySkill;
		this.question = question;
		this.options = options;
		this.mark = mark;
		this.level = level;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "industry_skill_id", nullable = false)
	public IndustrySkill getIndustrySkill() {
		return this.industrySkill;
	}

	public void setIndustrySkill(IndustrySkill industrySkill) {
		this.industrySkill = industrySkill;
	}

	@Column(name = "question", nullable = false)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question")
	public Set<Options> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Options> options) {
		this.options = options;
	}

	@Column(name = "mark", nullable = false)
	public int getMark() {
		return mark;
	}

	public void setMark(int mark) {
		this.mark = mark;
	}

	@Column(name = "level", nullable = false)
	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	
}
